version: "3.8"

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - PRIVATE_CHANNEL_ID=${PRIVATE_CHANNEL_ID}
      - PUBLIC_CHANNEL_ID=${PUBLIC_CHANNEL_ID}
      - PUBLIC_CHANNEL_USERNAME=${PUBLIC_CHANNEL_USERNAME}
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
